name: Build with ko

on:
  workflow_call: {}

jobs:
  ko-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ko-build/setup-ko@v0.9
      
      - name: Download semver.sh
        run: |
          mkdir -p scripts
          curl -sSL "https://raw.githubusercontent.com/Tiktai/helm-publish/refs/heads/main/scripts/semver.sh" -o scripts/semver.sh
          chmod +x scripts/semver.sh

      - name: Generate version with semver.sh
        id: semver
        run: |
          VERSION=$(scripts/semver.sh)
          VERSION=$(echo $VERSION | sed 's/+/_/g')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Build image with ko
        run: |
          ko build --sbom=none --platform=linux/amd64 --tags=$VERSION --image-label="repo_url=${{ github.event.repository.html_url }},commit_sha=${{ github.sha }}"
